// get all activities
GET http://localhost:5000/api/activities HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJib2IiLCJuYmYiOjE1NjcxNTA1NzgsImV4cCI6MTU2Nzc1NTM3OCwiaWF0IjoxNTY3MTUwNTc4fQ.N9FYKf42mCZNFLpt-o3LVpa8guH5S88NPO-DKlkCayoo-AKAZlTzuxKl7wD1JY8NvXUdRCXCzYUB6anL-2YOLw
###

// get one activity
GET http://localhost:5000/api/activities/05509eb9-66a0-4def-a05a-95656fad3167 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJib2IiLCJuYmYiOjE1NjcxNTA1NzgsImV4cCI6MTU2Nzc1NTM3OCwiaWF0IjoxNTY3MTUwNTc4fQ.N9FYKf42mCZNFLpt-o3LVpa8guH5S88NPO-DKlkCayoo-AKAZlTzuxKl7wD1JY8NvXUdRCXCzYUB6anL-2YOLw
###

// post a new activity
POST http://localhost:5000/api/activities HTTP/1.1
Content-Type: application/json

{
  "title": "Irenka's Birthday Party",
  "description": "Happy Birthday to you...",
  "category": "food",
  "date": "2019-10-20T20:00:00.9433767",
  "city": "Kiev",
  "venue": "Home"
}
###

// post a new activity
POST http://localhost:5000/api/activities HTTP/1.1
Content-Type: application/json

{}
###

// edit an activity
PUT http://localhost:5000/api/activities/3fd43847-6fc0-40e6-9413-8fa516f2102a HTTP/1.1
Content-Type: application/json

{
  "description": "White tie and tails!"
}
###

// delete an activity
DELETE http://localhost:5000/api/activities/921ed03c-eeda-4cf4-bd1e-842f60db933d HTTP/1.1
###