// get all activities
GET http://localhost:5000/api/activities HTTP/1.1
Authorization: {{token}}
###

// get one activity
GET http://localhost:5000/api/activities/1cb391c2-aab0-427e-8b88-8fcbd855496c HTTP/1.1
Authorization: {{token}}
###

// post a new activity
POST http://localhost:5000/api/activities HTTP/1.1
Authorization: {{token}}
Content-Type: application/json

{
  "title": "Irenka's Birthday Party",
  "description": "Happy Birthday to you...",
  "category": "food",
  "date": "2019-10-20T20:00:00.9433767",
  "city": "Kiev",
  "venue": "Home"
}
###

// post a new activity
POST http://localhost:5000/api/activities HTTP/1.1
Authorization: {{token}}
Content-Type: application/json

{}
###

// edit an activity
PUT http://localhost:5000/api/activities/3fd43847-6fc0-40e6-9413-8fa516f2102a HTTP/1.1
Authorization: {{token}}
Content-Type: application/json

{
  "description": "White tie and tails!"
}
###

// delete an activity
DELETE http://localhost:5000/api/activities/921ed03c-eeda-4cf4-bd1e-842f60db933d HTTP/1.1
Authorization: {{token}}
###

// attend an activity
POST http://localhost:5000/api/activities/05509eb9-66a0-4def-a05a-95656fad3167/attend HTTP/1.1
Authorization: {{token}}
###

// unattend an activity
DELETE http://localhost:5000/api/activities/05509eb9-66a0-4def-a05a-95656fad3167/attend HTTP/1.1
Authorization: {{token}}
###

// Bob, 01-09-2019
@token = Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJib2IiLCJuYmYiOjE1NjczNzM5MjQsImV4cCI6MTU2Nzk3ODcyNCwiaWF0IjoxNTY3MzczOTI0fQ.t5NcUEEgtJn4uGTLXKN3uvYP2rW2NVpgxlWa7rtV349Q6PBBSR84LyByGnwpXFczeOp298F3ZoAByaFOG7Nj7Q