// login user
POST http://localhost:5000/api/user/login HTTP/1.1
Content-Type: application/json

{
  "email": "bob@test.com",
  "password": "Pa$$w0rd"
}
###

// register a new user: success!
POST http://localhost:5000/api/user/register HTTP/1.1
Content-Type: application/json

{
  "displayName": "John",
  "username": "john",
  "email": "john@test.com",
  "password": "Pa$$w0rd"
}
###

// register a new user: error!
POST http://localhost:5000/api/user/register HTTP/1.1
Content-Type: application/json

{
  "displayName": "Bertrand",
  "username": "b",
  "email": "b@b.com",
  "password": "Bb$0"
}
###

// get current user
GET http://localhost:5000/api/user HTTP/1.1
Authorization: {{token}}

// Bob, 01-09-2019
@token = Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJib2IiLCJuYmYiOjE1NjczNzM5MjQsImV4cCI6MTU2Nzk3ODcyNCwiaWF0IjoxNTY3MzczOTI0fQ.t5NcUEEgtJn4uGTLXKN3uvYP2rW2NVpgxlWa7rtV349Q6PBBSR84LyByGnwpXFczeOp298F3ZoAByaFOG7Nj7Q